export { Template04 } from './Template04/Template04'
export { Template05 } from './Template05/Template05'

export { Template00 } from './Template00/Template00'
export { Template01 } from './Template01/Template01'
export { Template02 } from './Template02/Template02'
export { Template09 } from './Template09/Template09'
export { GothamTemplate } from './GothamTemplate/GothamTemplate'
export { IcotorialTemplate } from './IcotorialTemplate/IcotorialTemplate'
export { PlainButtonTemplate } from './PlainButtonTemplate/PlainButtonTemplate'
